name: Build and deploy the demo page
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          # See https://github.com/marketplace/actions/vuepress-deploy#create-a-personal-access-token
          # on how to create and store an access token in case a new one is
          # ever needed
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CNAME: code-switcher.padarom.xyz
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd demo && npm install && npm run build
          BUILD_DIR: src/.vuepress/dist
